/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _bigpinky_kitzel_0_0_h_
#define _bigpinky_kitzel_0_0_h_
//---------------------------------------------------------------------------------
extern const unsigned char bigpinky_kitzel_0_0[];
extern const int bigpinky_kitzel_0_0_size;
//---------------------------------------------------------------------------------
#endif //_bigpinky_kitzel_0_0_h_
//---------------------------------------------------------------------------------
